"""Demo NBA prop slate with display metadata for the dashboard."""

from __future__ import annotations

from datetime import date
from typing import Any

from betting_system.pipeline.predict import compute_edge


def _leg(
    *,
    player_id: str,
    player_name: str,
    position: str,
    game_id: str,
    matchup: str,
    market_type: str,
    line: float,
    odds_american: int,
    p_hit: float,
    score_final: str | None = None,
    actual_stat: float | None = None,
) -> dict[str, Any]:
    """Build one worthy leg dict with model edge and display fields."""
    er = compute_edge(p_hit, odds_american, min_edge=0.01, require_positive_ev=False)
    side = "OVER" if "over" in market_type else "UNDER"
    stat_label = "PTS" if "points" in market_type else ("AST" if "assists" in market_type else "REB")
    return {
        "game_id": game_id,
        "player_id": player_id,
        "player_name": player_name,
        "position": position,
        "matchup": matchup,
        "market_type": market_type,
        "market_label": stat_label,
        "side": side,
        "line": line,
        "odds_american": odds_american,
        "p_hit": float(er.p_hit),
        "edge": float(er.edge),
        "ev_per_unit": float(er.ev_per_unit),
        "worthy": er.worthy or er.edge > 0.02,
        "score_final": score_final,
        "actual_stat": actual_stat,
        "model_confidence_pct": round(float(er.p_hit) * 100, 1),
    }


def demo_worthy_legs() -> list[dict[str, Any]]:
    """Return a realistic tonight-style pool of player prop legs (demo data)."""
    slate_date = date.today().isoformat()
    return [
        _leg(
            player_id="lillard",
            player_name="D. Lillard",
            position="PG",
            game_id=f"den_por_{slate_date}",
            matchup="DEN @ POR",
            market_type="player_points_over",
            line=28.5,
            odds_american=-115,
            p_hit=0.62,
            score_final="DEN 121 @ POR 120 | FINAL",
            actual_stat=32.0,
        ),
        _leg(
            player_id="herro",
            player_name="T. Herro",
            position="SG",
            game_id=f"lac_mia_{slate_date}",
            matchup="LAC @ MIA",
            market_type="player_points_over",
            line=22.5,
            odds_american=-108,
            p_hit=0.58,
            score_final="LAC 110 @ MIA 115 | FINAL",
            actual_stat=24.0,
        ),
        _leg(
            player_id="langford",
            player_name="R. Langford",
            position="SF",
            game_id=f"hou_sas_{slate_date}",
            matchup="HOU @ SAS",
            market_type="player_points_over",
            line=14.5,
            odds_american=105,
            p_hit=0.57,
            score_final="HOU 109 @ SAS 118 | FINAL",
            actual_stat=18.0,
        ),
        _leg(
            player_id="roby",
            player_name="I. Roby",
            position="PF",
            game_id=f"hou_sas_{slate_date}",
            matchup="HOU @ SAS",
            market_type="player_points_under",
            line=12.5,
            odds_american=-112,
            p_hit=0.56,
            score_final="HOU 109 @ SAS 118 | FINAL",
            actual_stat=9.0,
        ),
        _leg(
            player_id="jokic",
            player_name="N. Jokic",
            position="C",
            game_id=f"den_por_{slate_date}",
            matchup="DEN @ POR",
            market_type="player_points_over",
            line=26.5,
            odds_american=-125,
            p_hit=0.64,
            score_final="DEN 121 @ POR 120 | FINAL",
            actual_stat=31.0,
        ),
        _leg(
            player_id="tatum",
            player_name="J. Tatum",
            position="SF",
            game_id=f"bos_nyk_{slate_date}",
            matchup="BOS @ NYK",
            market_type="player_points_over",
            line=27.5,
            odds_american=-110,
            p_hit=0.59,
        ),
        _leg(
            player_id="brunson",
            player_name="J. Brunson",
            position="PG",
            game_id=f"bos_nyk_{slate_date}",
            matchup="BOS @ NYK",
            market_type="player_assists_over",
            line=7.5,
            odds_american=-105,
            p_hit=0.61,
        ),
        _leg(
            player_id="sabonis",
            player_name="D. Sabonis",
            position="C",
            game_id=f"sac_lal_{slate_date}",
            matchup="SAC @ LAL",
            market_type="player_rebounds_over",
            line=12.5,
            odds_american=-118,
            p_hit=0.60,
        ),
        _leg(
            player_id="reaves",
            player_name="A. Reaves",
            position="SG",
            game_id=f"sac_lal_{slate_date}",
            matchup="SAC @ LAL",
            market_type="player_points_over",
            line=16.5,
            odds_american=102,
            p_hit=0.55,
        ),
        _leg(
            player_id="fox",
            player_name="D. Fox",
            position="PG",
            game_id=f"sac_lal_{slate_date}",
            matchup="SAC @ LAL",
            market_type="player_points_over",
            line=24.5,
            odds_american=-114,
            p_hit=0.58,
        ),
        _leg(
            player_id="booker",
            player_name="D. Booker",
            position="SG",
            game_id=f"phx_dal_{slate_date}",
            matchup="PHX @ DAL",
            market_type="player_points_over",
            line=25.5,
            odds_american=-112,
            p_hit=0.57,
        ),
        _leg(
            player_id="doncic",
            player_name="L. Doncic",
            position="PG",
            game_id=f"phx_dal_{slate_date}",
            matchup="PHX @ DAL",
            market_type="player_points_over",
            line=32.5,
            odds_american=-108,
            p_hit=0.63,
        ),
        _leg(
            player_id="ant",
            player_name="A. Edwards",
            position="SG",
            game_id=f"min_okc_{slate_date}",
            matchup="MIN @ OKC",
            market_type="player_points_over",
            line=26.5,
            odds_american=-115,
            p_hit=0.60,
        ),
        _leg(
            player_id="sga",
            player_name="S. Gilgeous-Alexander",
            position="PG",
            game_id=f"min_okc_{slate_date}",
            matchup="MIN @ OKC",
            market_type="player_points_over",
            line=30.5,
            odds_american=-120,
            p_hit=0.62,
        ),
        _leg(
            player_id="holmgren",
            player_name="C. Holmgren",
            position="C",
            game_id=f"min_okc_{slate_date}",
            matchup="MIN @ OKC",
            market_type="player_rebounds_over",
            line=9.5,
            odds_american=-106,
            p_hit=0.56,
        ),
        _leg(
            player_id="banchero",
            player_name="P. Banchero",
            position="PF",
            game_id=f"orl_atl_{slate_date}",
            matchup="ORL @ ATL",
            market_type="player_points_over",
            line=23.5,
            odds_american=-110,
            p_hit=0.58,
        ),
        _leg(
            player_id="young",
            player_name="T. Young",
            position="PG",
            game_id=f"orl_atl_{slate_date}",
            matchup="ORL @ ATL",
            market_type="player_assists_over",
            line=9.5,
            odds_american=100,
            p_hit=0.57,
        ),
        _leg(
            player_id="mobley",
            player_name="E. Mobley",
            position="PF",
            game_id=f"cle_chi_{slate_date}",
            matchup="CLE @ CHI",
            market_type="player_rebounds_over",
            line=10.5,
            odds_american=-113,
            p_hit=0.59,
        ),
        _leg(
            player_id="garland",
            player_name="D. Garland",
            position="PG",
            game_id=f"cle_chi_{slate_date}",
            matchup="CLE @ CHI",
            market_type="player_points_over",
            line=19.5,
            odds_american=-107,
            p_hit=0.56,
        ),
        _leg(
            player_id="wembanyama",
            player_name="V. Wembanyama",
            position="C",
            game_id=f"hou_sas_{slate_date}",
            matchup="HOU @ SAS",
            market_type="player_points_over",
            line=21.5,
            odds_american=-109,
            p_hit=0.61,
        ),
        _leg(
            player_id="murray",
            player_name="J. Murray",
            position="PG",
            game_id=f"den_por_{slate_date}",
            matchup="DEN @ POR",
            market_type="player_assists_over",
            line=6.5,
            odds_american=-102,
            p_hit=0.55,
        ),
        _leg(
            player_id="adebayo",
            player_name="B. Adebayo",
            position="C",
            game_id=f"lac_mia_{slate_date}",
            matchup="LAC @ MIA",
            market_type="player_rebounds_over",
            line=10.5,
            odds_american=-111,
            p_hit=0.58,
        ),
    ]
