"""Curated prediction-market fixtures for offline/demo operation."""

from __future__ import annotations

from datetime import datetime, timedelta, timezone

NOW = datetime.now(timezone.utc)


def curated_market_rows() -> list[dict]:
    """Return realistic active-style markets across major categories."""
    close = NOW + timedelta(days=90)
    return [
        {
            "market_id": "fix-fed-july-cut",
            "event_id": "fed-july-2026",
            "venue": "polymarket",
            "category": "Econ",
            "question": "Fed cuts rates at July 2026 FOMC meeting?",
            "outcome": "YES",
            "yes_price": 0.54,
            "volume": 2_400_000,
            "liquidity": 180_000,
            "closes_at": close,
            "price_history_market": [0.48, 0.49, 0.50, 0.51, 0.52, 0.53, 0.54],
            "source": "fixture",
        },
        {
            "market_id": "fix-btc-150k",
            "event_id": "btc-150k-2026",
            "venue": "polymarket",
            "category": "Crypto",
            "question": "BTC above $150,000 on Dec 31, 2026?",
            "outcome": "YES",
            "yes_price": 0.31,
            "volume": 8_100_000,
            "liquidity": 420_000,
            "closes_at": close + timedelta(days=180),
            "price_history_market": [0.22, 0.24, 0.26, 0.27, 0.28, 0.30, 0.31],
            "source": "fixture",
        },
        {
            "market_id": "fix-2028-election",
            "event_id": "us-2028-pres",
            "venue": "kalshi",
            "category": "Politics",
            "question": "Republican wins 2028 US presidential election?",
            "outcome": "YES",
            "yes_price": 0.49,
            "volume": 14_200_000,
            "liquidity": 950_000,
            "closes_at": close + timedelta(days=800),
            "price_history_market": [0.44, 0.45, 0.46, 0.47, 0.48, 0.48, 0.49],
            "source": "fixture",
        },
        {
            "market_id": "fix-wc-winner",
            "event_id": "wc-2026-winner",
            "venue": "polymarket",
            "category": "Sports",
            "question": "Brazil wins 2026 FIFA World Cup?",
            "outcome": "YES",
            "yes_price": 0.18,
            "volume": 3_200_000,
            "liquidity": 210_000,
            "closes_at": close + timedelta(days=120),
            "price_history_market": [0.14, 0.15, 0.15, 0.16, 0.17, 0.17, 0.18],
            "source": "fixture",
        },
        {
            "market_id": "fix-love-island",
            "event_id": "love-island-us-2026",
            "venue": "kalshi",
            "category": "Culture",
            "question": "Love Island USA Season 7 winner from original coupling?",
            "outcome": "YES",
            "yes_price": 0.27,
            "volume": 890_000,
            "liquidity": 55_000,
            "closes_at": close + timedelta(days=45),
            "price_history_market": [0.20, 0.21, 0.23, 0.24, 0.25, 0.26, 0.27],
            "source": "fixture",
        },
        {
            "market_id": "fix-cpi-sub2",
            "event_id": "cpi-q3-2026",
            "venue": "kalshi",
            "category": "Econ",
            "question": "US CPI YoY below 2.0% in Q3 2026?",
            "outcome": "YES",
            "yes_price": 0.28,
            "volume": 1_200_000,
            "liquidity": 88_000,
            "closes_at": close + timedelta(days=150),
            "price_history_market": [0.20, 0.21, 0.23, 0.24, 0.26, 0.27, 0.28],
            "source": "fixture",
        },
        {
            "market_id": "fix-eth-10k",
            "event_id": "eth-10k-2026",
            "venue": "polymarket",
            "category": "Crypto",
            "question": "ETH above $10,000 by end of 2026?",
            "outcome": "YES",
            "yes_price": 0.12,
            "volume": 3_500_000,
            "liquidity": 190_000,
            "closes_at": close + timedelta(days=180),
            "price_history_market": [0.08, 0.09, 0.09, 0.10, 0.11, 0.11, 0.12],
            "source": "fixture",
        },
        {
            "market_id": "fix-senate-2026",
            "event_id": "senate-2026",
            "venue": "kalshi",
            "category": "Politics",
            "question": "Democrats hold Senate after 2026 midterms?",
            "outcome": "YES",
            "yes_price": 0.38,
            "volume": 5_600_000,
            "liquidity": 310_000,
            "closes_at": close + timedelta(days=500),
            "price_history_market": [0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38],
            "source": "fixture",
        },
        {
            "market_id": "fix-sp500-7000",
            "event_id": "sp500-7000-2026",
            "venue": "kalshi",
            "category": "Econ",
            "question": "S&P 500 closes above 7,000 in 2026?",
            "outcome": "YES",
            "yes_price": 0.42,
            "volume": 4_100_000,
            "liquidity": 260_000,
            "closes_at": close + timedelta(days=200),
            "price_history_market": [0.35, 0.36, 0.38, 0.39, 0.40, 0.41, 0.42],
            "source": "fixture",
        },
        {
            "market_id": "fix-gta-vi",
            "event_id": "gta-vi-2026",
            "venue": "polymarket",
            "category": "Culture",
            "question": "GTA VI releases before Jan 1, 2027?",
            "outcome": "YES",
            "yes_price": 0.62,
            "volume": 960_000,
            "liquidity": 72_000,
            "closes_at": close + timedelta(days=180),
            "price_history_market": [0.52, 0.54, 0.56, 0.58, 0.59, 0.61, 0.62],
            "source": "fixture",
        },
    ]
